apiVersion: v1
kind: Service
metadata:
  name: fastapi
  namespace: todo-app
spec:
  selector:
    app: fastapi
  ports:
    - protocol: TCP
      port: 30051
      targetPort: 8000
  type: LoadBalancer 