apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  # Le mot de passe 'mypassword' encodé en base64
  POSTGRES_PASSWORD: bXlwYXNzd29yZA==
  POSTGRES_USER: cG9zdGdyZXM=  # 'postgres' en base64 